# Generated by Django 5.0.3 on 2024-03-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=20)),
                ('data_nasc', models.DateField()),
                ('email', models.CharField(max_length=80)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
            options={
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='EstadoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Estados dos Imóveis',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='RankingImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Rankings',
            },
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Imóveis',
            },
        ),
        migrations.CreateModel(
            name='TipoLogradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Logradouros',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'UFs',
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Compradores',
            },
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Locatários',
            },
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('complemento', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipologradouro')),
            ],
            options={
                'verbose_name_plural': 'Logradouros',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('area_construida', models.CharField(max_length=50)),
                ('n_comodos', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=40)),
                ('n_vagas', models.PositiveIntegerField()),
                ('cep', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadoimovel')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.logradouro')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rankingimovel')),
                ('tipo_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoimovel')),
                ('tipo_logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipologradouro')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf')),
            ],
            options={
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formapagamento')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imovel')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comprador')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formapagamento')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.imovel')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.locatario')),
            ],
            options={
                'verbose_name_plural': 'Locações',
            },
        ),
    ]
